account/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as authviews
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'account'

urlpatterns = [
    url(r'^$', views.profile, name='home'),
    url(r'^login/$', csrf_exempt(views.login_user),name='login'),
    url(r'^logout/$', views.logout_user,name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^forgotpassword/$', views.forgot_password, name='forgotpassword'),
    url(r'^changepassword/$', views.change_password, name='changepassword'),
    url(r'^changepassword/$', views.change_password, name='changepassword'),
    url(r'^editdetails/$', views.edit_details, name='editdetails'),
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns = [	
    url(r'^$', views.home, name='home'),
    url(r'^about$', views.about, name='about'),
    ]

library-management-system/urls.py
"""
Definition of urls for VCWeb.
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
#from mess import views
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    #url(r'^$', views.test, name='home'),
    # url(r'^vcwebsite/', include('vcwebsite.vcwebsite.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', logout),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls')),
    url(r'^library/', include('library.urls')),
    url(r'^account/', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns+=[
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
        url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT }),
    ]

library/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'library'

urlpatterns = [
    url(r'^$', views.LibHome, name='home'),
    url(r'^index/$', views.BookIndex.as_view(), name='library'),
    url(r'^book/(?P<id>[0-9]+)/$', views.BookDetail, name='detail'),
    url(r'^book/edit/(?P<pk>[0-9]+)/$', login_required(views.BookEdit.as_view()), name='edit'),
    url(r'^new/$', views.NewForm, name='new'),
    url(r'^add/$', login_required(views.BookAdd.as_view()), name='add'),
    url(r'^request/(?P<id>[0-9]+)/issue/$', views.IssueBook, name='issue'),
    url(r'^request/(?P<id>[0-9]+)/return/$', views.ReturnBook, name='return'),
    url(r'^request/(?P<id>[0-9]+)/collect/$', views.CollectBook, name='collect'),
    url(r'^request/(?P<id>[0-9]+)/undoreturn/$', views.UndoReturn, name='undoreturn'),
    url(r'^search/$', views.Search, name='search'),
    url(r'^admin_dashboard/$', views.adminDash, name='admin_dash'),
    url(r'^dashboard/$', views.UserDashboard, name='user_dashboard'),
    url(r'^del_request/(?P<id>\d+)/$', views.deleteRequest, name="delete_request"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'home/home.html')

def about(request):
    return render(request,'home/about.html')

home/templates/home/about.html
{% extends 'home/base.html' %}
{% block title %} About {% endblock %}
{% block styles %}
{% load staticfiles %}
{% endblock %}
{% block content %}
    <div class="container-fluid text-center">
        <h1><u>E Commarce Project</u></h1><br>
        <h4>1. Bibhas Mondal</h3><br>
        <h4>2. Tamoghna Rakshit</h3><br>
        <h4>3. Indranil Chowdhury</h3><br>
        <h4>4. Sourav Kalsa</h3><br>
        <h4>5 Samapti Adhikari</h3>
    </div>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title id="title">{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="shortcut icon" href="{% static 'home/favicon.ico' %}" />
        <link rel="icon" href="{% static 'home/logo.png' %}" type="image/x-icon" />
        <link rel="stylesheet" href="{% static 'home/bootstrap.min.css' %}">
        <link href="{% static 'home/latofont.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'home/montserratfont.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'home/jquery.min.js' %}"></script>
        <script src="{% static 'home/bootstrap.min.js' %}"></script>
        <link href="{% static 'home/materialicons.css' %}" rel="stylesheet">
        <link href="{% static 'home/font-awesome.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'home/base.css' %}">
        {% block styles %}
        {% endblock %}
        {% load get_view %}
    </head>
    <body>
        {% if not request|isappview %}
            <nav class="navbar navbar-default navbar-fixed-top">

                <div class="container-fluid">

                    <div style="float:right;font-size:20px;margin-top:10px;margin-right:-10px;margin-left:110px">
                        {% if request.user.is_authenticated %}
                            <a data-toggle="collapse" href="#navLogin" ><img src="data:image/jpeg;base64,{{request.user.student.dp}}" style="width:40px;height:40px;margin-top:5px;" class="img-circle" alt="{{request.user.student|sf }}"></a>
                        {% else %}
                            <a data-toggle="collapse" href="#navLogin" class="navlogin"><i style="margin-top:15px;margin-left:-35px" class="material-icons">&#xe7fe;</i><span class="tooltiptext">Sign in</span></a>
                        {% endif %}
                    </div>

                    <div id="navLogin" class="collapse" style="position:absolute;background-color:#e0e0de;right:0;top:63px;border-radius:5px;z-index:1;">

                        <div>
                            <span class="rightuppertriangle"></span><span class="leftuppertriangle"></span>
                        </div>

                        <div class="container-fluid">
                            {% if request.user.is_authenticated %}
                                <div class="row" style="padding-top:10px;padding-bottom:10px;padding-right:10px;padding-left:10px">
                                    <div class="user">
                                        <a href="{% url 'account:home' %}"><img src="data:image/jpeg;base64,{{request.user.student.dp}}" style="width:60px;height:60px" class="img-circle" alt="{{request.user.student|sf }}"><span class="tooltiptext">Account info</span></a>
                                    </div>
                                    <div style="margin-top:-10px;float:left">
                                        <b style="font-size:15px;color:black">{{request.user.student}}</b><br />
                                        <label style="font-size:11px;letter-spacing:0px">{{request.user.email}}</label>
                                    </div><br />
                                    <button id="logout" class="btn btn-primary" style="float:right;letter-spacing:2px">Sign out</button><br />
                                </div>
                            {% else %}
                                {% include 'account/login.html' %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="navbar-header">
                        <button id="navbtn" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" style="float:left">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="text-center" href="{% url 'home:home' %}"><img src="{% static 'home/library_logo.png' %}" alt="VC" style="width:300px;height:60px;margin-top:5px;margin-bottom:5px"></a>
                    </div>

                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav navbar-right">

                        {% if 'home' in request.resolver_match.app_name and 'about' not in request.path %}
                            <li  class="active"><a>HOME</a></li>
                        {% else %}
                            <li><a href="{% url 'home:home' %}">HOME</a></li>
                        {% endif %}

                        {% if 'library' in request.resolver_match.app_name %}
                            <li class="active"><a href="{% url 'library:home' %}">LIBRARY</a></li>
                        {% else %}
                            <li><a href="{% url 'library:home' %}">LIBRARY</a></li>
                        {% endif %}

                        {% if 'about' in request.path %}
                            <li class="active"><a href="{% url 'home:about' %}">ABOUT</a></li>
                        {% else %}
                            <li><a href="{% url 'home:about' %}">ABOUT</a></li>
                        {% endif %}

                        </ul>
                    </div>

                </div>

            </nav>

            <div id="myBody" style="position:absolute;left:0;right:0;top:70px;bottom:64px;overflow-y:auto;overflow-x:hidden">
                {% block mininav %}
                {% endblock %}
        {% else %}
            <div style="position:absolute;left:0;right:0;top:0px;bottom:0px;overflow-y:auto;overflow-x:hidden">
        {% endif %}

            {% if messages %}
                <div class="container-fluid">
                    {% for message in messages %}
                        <label class="{{ message.tags }}">
                            {{ message }}
                        </label>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="container-fluid row">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        {% if not request|isappview %}
            <!-- Footer -->
            <footer class="navbar-fixed-bottom navbar-inverse container-fluid text-center" >
                <p style="text-align:center">&copy; Copyright 2018 | Library Management<br>All Rights Reserved</p>
            </footer>
        {% endif %}
        <script src="{% static 'home/base.js' %}" type="text/javascript"></script>
    </body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% block title %} Home {% endblock %}
{% block styles %}
{% load staticfiles %}
{% endblock %}
{% block content %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img src="{% static 'home/IMG1.jpg' %}" alt="IMG" id="img1">
            <div class="carousel-caption">
              <p style="color:black">I had found my religion: nothing seemed more important to me than a book. I saw the library as a temple.<br>—Jean-Paul Sartre</p>
            </div>
          </div>

          <div class="item">
            <img src="{% static 'home/IMG2.jpg' %}" alt="IMG" id="img2">
            <div class="carousel-caption">
              <p>The only thing that you absolutely have to know, is the location of the library.<br>—Albert Einstein</p>
            </div>
          </div>

          <div class="item">
              <img src="{% static 'home/IMG3.jpg' %}" alt="IMG" id="img3">
              <div class="carousel-caption">
                <p>Literacy is the most basic currency of the knowledge economy.<br>—Barack Obama</p>
              </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
    <script src="{% static 'home/home.js' %}" type="text/javascript"></script >    
{% endblock %}