home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns = [	
    url(r'^$', views.home, name='home'),
    url(r'^about$', views.about, name='about'),
    ]

library-management-system/urls.py
"""
Definition of urls for VCWeb.
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
#from mess import views
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    #url(r'^$', views.test, name='home'),
    # url(r'^vcwebsite/', include('vcwebsite.vcwebsite.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', logout),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls')),
    url(r'^library/', include('library.urls')),
    url(r'^account/', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns+=[
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
        url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT }),
    ]

library/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'library'

urlpatterns = [
    url(r'^$', views.LibHome, name='home'),
    url(r'^index/$', views.BookIndex.as_view(), name='library'),
    url(r'^book/(?P<id>[0-9]+)/$', views.BookDetail, name='detail'),
    url(r'^book/edit/(?P<pk>[0-9]+)/$', login_required(views.BookEdit.as_view()), name='edit'),
    url(r'^new/$', views.NewForm, name='new'),
    url(r'^add/$', login_required(views.BookAdd.as_view()), name='add'),
    url(r'^request/(?P<id>[0-9]+)/issue/$', views.IssueBook, name='issue'),
    url(r'^request/(?P<id>[0-9]+)/return/$', views.ReturnBook, name='return'),
    url(r'^request/(?P<id>[0-9]+)/collect/$', views.CollectBook, name='collect'),
    url(r'^request/(?P<id>[0-9]+)/undoreturn/$', views.UndoReturn, name='undoreturn'),
    url(r'^search/$', views.Search, name='search'),
    url(r'^admin_dashboard/$', views.adminDash, name='admin_dash'),
    url(r'^dashboard/$', views.UserDashboard, name='user_dashboard'),
    url(r'^del_request/(?P<id>\d+)/$', views.deleteRequest, name="delete_request"),
]

library/models.py
from __future__ import unicode_literals
from datetime import datetime, timedelta, date
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User as AuthUser

# Create your models here.


class Subject(models.Model):
    title = models.CharField(max_length=50)
    code = models.CharField(max_length=2)
    #branches = models.CharField(max_length=200)

    def __str__(self):
        return self.title + ' (' + self.code + ')'


class Book(models.Model):
    author = models.CharField(max_length=250)
    title = models.CharField(max_length=500, unique=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='library/images', blank=True)
    publisher = models.CharField(max_length=50, blank=True)
    issued = models.BooleanField(default=False)
    issued_name = models.ForeignKey(AuthUser,blank=True, null=True,on_delete=models.CASCADE)

    def get_edit_url(self):
        return reverse('library:edit', kwargs={'pk': self.id})

    def get_absolute_url(self):
        return reverse('library:detail', kwargs={'id': self.id})

    class Meta:
        ordering = ('issued', 'subject', '-title', '-author',)

    def __str__(self):
        return self.author + '-' + self.title + ' ---- ' + (self.subject).code + str(self.pk)


class Request(models.Model):

    """
    An explanation regarding status and retstatus is in order, obviously.

    To make things simple, let us consider all
    the forms the combination of these two Booleans can take: 00, 01, 10, 11.
    00: User makes a reequest, and both are inititalised as False.
    10: The book has been delivered, request has been marked to be completed.
    11: The issuer wants to return the book. He expresses this desire by marking retstatus as True.
    01: The book has been returned to its place of glory on the library shelf, and the given request has completed its cycle. 
    Now it only awaits the attention of a superuser who checks everything and allows it to dissolve into digital oblivion.
    """

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(AuthUser, blank=True, null=True, default=None, related_name='requests')
    # name = models.CharField(max_length=30)
    # remarks = models.TextField(blank=True)
    status = models.BooleanField(default=False)
    retstatus = models.BooleanField(default=False)
    request_date = models.DateField(auto_now_add=True)
    issue_date = models.DateField(blank=True, null=True)
    return_request_date = models.DateField(blank=True, null=True)
    return_date = models.DateField(blank=True, null=True)
    issued_by = models.ForeignKey(AuthUser, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='requests_completed')
    returned_by = models.ForeignKey(AuthUser, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='returns_completed')

    def due_date(self):
        '''Adds 21 days to the issue date and returns a date when the book should be returned if it has been
        requeested by somebody else. A soft limit.'''

        return self.issue_date + timedelta(days=15)
    
    def is_overdue(self):
        """Return Boolean depending on whether the book is overdue."""
        return date.today() > self.due_date()

    def is_wanted(self):
        """Returns whether the book issued is wanted by someone else."""
        bk = self.book
        reqs = Request.objects.filter(book=bk, status=False, retstatus=False)
        return len(reqs)

    def __str__(self):
        if self.status == True:
            return str(self.user) + "'s request completed. Until: " + str(self.due_date())
        return str(self.user) + ' requested a Book'

    def get_absolute_url(self):
        return reverse('library:req')

    def get_issue_url(self):
        return reverse('library:issue', kwargs={'id': self.id})

    def get_return_url(self):
        return reverse('library:return', kwargs={'id': self.id})

    def get_collect_url(self):
        return reverse('library:collect', kwargs={'id': self.id})

    def get_undo_url(self):
        return reverse('library:undoreturn', kwargs={'id': self.id})


class New(models.Model):
    details = models.TextField()
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name + ' wants an unregistered book.'

library/forms.py
from django import forms
from .models import *

class BookRequest(forms.ModelForm):
    remarks = forms.CharField(required=False,widget=forms.Textarea(attrs={'placeholder': 'Remarks','max_length': 100}))
    class Meta:
        model = Request
        fields = ['remarks'] 

class New(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Name','max_length': 100}))
    details = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Details','max_length': 100}))
    class Meta:
        model = New
        fields = ['name','details']

class BookAdd(forms.ModelForm):
    title = forms.CharField(label='Title',widget=forms.TextInput(attrs={'placeholder': 'Title','max_length': 100}))
    author = forms.CharField(label='Author',widget=forms.TextInput(attrs={'placeholder': 'Author','max_length': 100}))
    subject = forms.ModelChoiceField(label='Subject',widget=forms.Select(attrs={'max_length': 16}),queryset = Subject.objects.all(),initial=None)
    publisher = forms.CharField(label='Publisher',widget=forms.TextInput(attrs={'placeholder': 'Publisher','max_length': 100}))
    image = forms.ImageField(label='Image',widget=forms.FileInput(attrs={'type':'file','placeholder': 'Image','max_length': 100}))
    class Meta:
        model = Book
        fields = ['title','author','subject','publisher','image']

library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.views import generic
from .models import Book, Subject
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from .forms import *
from django.contrib import messages
from .models import Book
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import datetime

# Create your views here.

"""class Subject(CreateView):
    model = Subject
    fields = ['title','code']

class BookCreate(CreateView):
    model = Book
    fields = ['author', 'title', 'subject', 'image']

class BookEdit(UpdateView):
    model = Book
    fields = ['author', 'title', 'subject', 'image']"""


class BookIndex(generic.ListView):
    template_name = 'library/index.html'
    context_object_list = 'object_list'

    def get_queryset(self):
        return Book.objects.all()


def BookDetail(request, id):
    reqbook = get_object_or_404(Book, id=id)
    if request.method == 'GET':
        form = BookRequest(None)
        return render(request, 'library/detail.html', {'form': form, 'reqbook': reqbook})
    if request.method == 'POST' and request.user.is_authenticated:
        form = BookRequest(request.POST)
        if form.is_valid():
            req = form.save(commit=False)
            req.user = request.user
            req.book = reqbook  # adding current book to the request.
            req.save()
            if reqbook.issued == True:
                messages.warning(
                    request, 'This book has already been issued out,')
            messages.success(request, 'Your request for ' + reqbook.title + ' has been registered.')
        return render(request, 'library/detail.html', {'form': form, 'reqbook': reqbook})


def NewForm(request):
    if request.method == 'POST':
        form = New(request.POST)
        if form.is_valid():
            form.save()
            message.success(request, 'Your request has been submitted.')
    else:
        form = New(None)
    return render(request, 'library/new.html', {'form': form})


class BookAdd(CreateView):
    template_name = 'library/add.html'
    form_class = BookAdd


class BookEdit(UpdateView):
    model = Book
    template_name = 'library/edit_book.html'
    fields = ['title', 'author', 'subject', 'publisher', 'image']


@login_required
def IssueBook(request, id):
    req = get_object_or_404(Request, id=id)
    book = req.book
    if not request.user.is_staff:
        messages.warning(request, 'You aren\'t authorized to issue. Please contact a librarian.')
        return redirect('library:home')
    if not book.issued:
        book.issued = True
        book.issued_name = req.user
        book.save()
        req.status = True
        req.issued_by = request.user
        req.issue_date = date.today()
        req.save()
        messages.success(
            request, 'You issued out this book to ' + req.user.first_name + '.')
        return redirect('library:admin_dash')
    else:
        messages.error(
            request, 'Oops! Something went wrong! Looks like this book was already issued.')
    return redirect('library:admin_dash')

@login_required
def ReturnBook(request, id):
    req = get_object_or_404(Request, id=id)
    book = req.book
    if not (book.issued and (req.user==request.user or request.user.is_staff)):
        messages.warning(
            request, 'It doesn\'t look like this book had been issued out to you. Contact an admin.')
    req.retstatus = True
    req.return_request_date = date.today()
    req.save()
    messages.success(request, 'You asked for this book to be collected.')
    return redirect('library:user_dashboard')

@login_required
def CollectBook(request, id):
    req = get_object_or_404(Request, id=id)
    book = req.book
    if not request.user.is_staff:
        messages.warning(request, 'You aren\'t authorized to collect. Please contact a librarian.')
        return redirect('library:home')
    if not book.issued:
        messages.warning(
            request, 'It doesn\'t look like this book had been issued out. Contact an admin.')
    else:
        book.issued = False
        book.save()
        req.status = False
        req.returned_by = request.user
        req.return_date = date.today()
        req.save()
        messages.success(request, 'You collected this book.')
    return redirect('library:admin_dash')


def UndoReturn(request, id):
    req = get_object_or_404(Request, id=id)
    req.retstatus = False
    req.save()
    messages.success(request, "This return was cancelled.")
    return redirect('library:user_dashboard')


import re
import operator


def Search(request):
    if request.GET.get('q'):
        global query
        message = "you submitted " + request.GET['q']
        query = request.GET['q']
        q = query.lower()
        q = re.split('\s|\,', q)
        q = [x for x in q if x]
        all_books = Book.objects.all()
        results = []
        for book in all_books:
            slug = book.author.lower() + '-' + book.title.lower() + '-' + \
                book.subject.title.lower() + '-' + book.publisher.lower()
            # results.append(slug)
            count = 0
            for tag in q:
                if tag in slug:
                    count += 1
            if count == len(q):
                thisresult = [book, count]
                results.append(thisresult)
        results.sort(key=operator.itemgetter(1), reverse=True)
        message += str(q)
        message += str(results)

    else:
        message = "Nothing submitted!"
        results = []
        eresults = []
        query = ''

    return render(request, 'library/search.html', {'message': message, 'query': query, 'results': results})


# def FindEbooks(string):
#   httpslibgen.io/search.php?req=bachelor of arts&lg_topic=libgen&open=0&view=simple&res=25&phrase=1&column=def

def LibHome(request):
    return render(request, 'library/library.html')

@login_required
def UserDashboard(request):
    """View for library dashboard of individual, non-librarian user."""

    context = {}

    my_requests = Request.objects.filter(user = request.user)
    context['all'] = my_requests
    context['req_00'] = my_requests.filter(status=0, retstatus=0)
    context['req_01'] = my_requests.filter(status=0, retstatus=1)
    context['req_11'] = my_requests.filter(status=1, retstatus=1)
    context['req_10'] = my_requests.filter(status=1, retstatus=0)

    # context['req_01'] = context['req_01'].filter(self.due_date()>datetime.datetime.today())

    return render(request, 'library/user_dashboard.html', context)

def deleteRequest(request, id):
    """View to delete a request if it is archived or requested, only."""

    r = get_object_or_404(Request, id=id)
    if (request.user.is_staff or r.user == request.user) and r.status==False and r.retstatus==False:
        Request.objects.get(id=id).delete()
        messages.success(request, "Request successfully cancelled.")
    else:
        messages.error(request, "You may not permission to delete that request.")
    return redirect('library:user_dashboard')

@login_required
def adminDash(request):
    """Dashboard for librarian."""

    r = Request.objects.all()
    req_00 = r.filter(status=0, retstatus=0)
    req_01 = r.filter(status=0, retstatus=1)
    req_10 = r.filter(status=1, retstatus=0)
    req_11 = r.filter(status=1, retstatus=1)

    # req_pending = req_00.filter(book__issued==False)
    # ret_overdue = req_10.filter(due_date() < datetime.today())

    context = {
        # 'requests': req_pending,
        # 'overdue': ret_overdue,
        # 'returns': req_11
        'req_00': req_00,
        'req_01': req_01,
        'req_10': req_10,
        'req_11': req_11,
    }

    return render(request, 'library/dashboard.html', context)

library/templates/library/add.html
{% extends 'home/base.html' %}
{% block title %} Add Book | Library {% endblock %}
{% block mininav %}
    {% include 'library/mininav.html' %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="col-sm-5 col-sm-offset-3 text-center">
            <h2>Add a book:</h2><h6>Authors' names should be last-name-only, separated by only a comma. E.g.: 'Roberts', 'Das, Pal', etc. <br>Images aren't necessary. <br> For multiple copies of the same book, add #2, or #3  after the title.</h6>
        </div>
        <div class="col-sm-4 col-sm-offset-4">
            <form class="form-horizontal" action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {% include 'library/form-template.html' %}
                    <div style="float:left">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

library/templates/library/dashboard.html
{% extends 'home/base.html' %}
{% block title %} Library | Dashboard {% endblock %}
{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'library/dashboard.css'%}">
{% endblock %}
{% block mininav %}
    {% include 'library/mininav.html' %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#req_00">Request</a></li>
            <li><a data-toggle="tab" href="#req_10">Issued Out</a></li>
            <li><a data-toggle="tab" href="#req_11">Request for Returns</a></li>
            <li style="display:none"><a data-toggle="tab" href="#rft">Request for Transfers</a></li>
        </ul>
        <div class="tab-content">
            <div id="req_00" class="tab-pane fade in active">
                <div class="row">
                    {% for req in req_00 %}
                        <div class="req_outer col-sm-4 col-md-3">
                            <div class="req_inner">
                                <div class="topbar">
                                    <b>{{ req.book.subject.code }}{{ req.book.id }}</b>
                                    {{ req.book.title }}
                                    <br>
                                    <b>{{ req.user.first_name }} {{ req.user.last_name }}</b> requested this.
                                    <div class="toggler"><i class="fa fa-arrow-right"></i></div>
                                </div>
                                <div class="body"> 
                                    <div class="book">{{ req.book.title }}</div>
                                    <div class="author">
                                        <span class="title">Author:&nbsp;</span>
                                        {{ req.book.author }}
                                    </div>
                                    <div class="date">
                                        <span class="title">Date requested:&nbsp;</span>
                                        {{ req.request_date }}
                                    </div>
                                    <a href="{% url "library:delete_request" req.id %}" style="margin-left:-100px">
                                        <div class="btn btn-warning">Cancel</div>
                                    </a>
                                    <a href="{% url "library:issue" req.id %}" style="margin-left:50px">
                                        <div class="btn btn-success">Issue</div>
                                    </a>
                                </div>
                                <br><br>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="req_10" class="tab-pane fade">
                <div class="row">
                    {% for req in req_10 %}
                        <div class="req_outer col-sm-4 col-md-3">
                            <div class="req_inner">
                                <div class="topbar">
                                    <b>{{ req.book.subject.code }}{{ req.book.id }}</b>
                                    {{ req.book.title }}
                                    <div class="toggler"><i class="fa fa-arrow-right"></i></div>
                                </div>
                                <div class="body"> 
                                    <div class="book">{{ req.book.title }}</div>
                                    <div class="author"><span class="title">Author:&nbsp;</span>
                                        {{ req.book.author }}</div>
                                    <div class="date"><span class="title">Date requested:&nbsp;</span>
                                        {{ req.request_date }}</div>
                                    <div class="date"><span class="title">Status:&nbsp;</span>
                                        {% if req.is_overdue %}
                                            {% if req.is_wanted %}
                                                <div class="stat_red"></div>
                                                Return Pending
                                            {% else %}
                                                <div class="stat_yellow"></div>
                                                Overdrawn
                                            {% endif %}
                                        {% else %}
                                            <div class="stat_green"></div>
                                            OK
                                        {% endif %}
                                    </div>
                                </div>
                                <br><br>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="req_11" class="tab-pane fade">
                <div class="row">
                    {% for req in req_11 %}
                        <div class="req_outer col-sm-4 col-md-3">
                            <div class="req_inner">
                                <div class="topbar">
                                    <b>{{ req.book.subject.code }}{{ req.book.id }}</b>
                                    {{ req.book.title }}
                                    <div class="toggler"><i class="fa fa-arrow-right"></i></div>
                                </div>
                                <div class="body"> 
                                    <div class="book">{{ req.book.title }}</div>
                                    <div class="author">
                                        <span class="title">Author:&nbsp;</span>
                                        {{ req.book.author }}
                                    </div>
                                    <div class="date">
                                        <span class="title">Date requested:&nbsp;</span>
                                        {{ req.request_date }}
                                    </div>
                                    <a class="btn btn-success" href="{{ req.get_collect_url }}">Collect</a>
                                </div>
                                <br><br>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="rft" class="tab-pane fade">
                <!--Pending-->
                <div class="row">
                    <div class="container-fluid" style="padding-left:30px"><h1>Pending</h1></div>
                    <div class="req_outer col-sm-4 col-md-3">
                        <div class="req_inner">
                            <div class="topbar">
                                <b>{{ req.book.subject.code }}{{ req.book.id }}</b>
                                {{ req.book.title }}
                                <div class="toggler"><i class="fa fa-arrow-right"></i></div>
                            </div>
                            <div class="body"> 
                                <div class="book">{{ req.book.title }}</div>
                                <div class="author"><span class="title">Author:&nbsp;</span>
                                    {{ req.book.author }}</div>
                                <div class="date"><span class="title">Date requested:&nbsp;</span>
                                    {{ req.request_date }}</div>
                                <div class="btn btn-warning">Cancel</div>                            
                            </div>
                            <br><br>
                        </div>
                    </div>            
                </div>
                <!--Completed-->
                <div class="row" style="padding-bottom:40px">
                    <div class="container-fluid" style="padding-left:30px"><h1>Complete</h1></div>
                    <div class="req_outer col-sm-4 col-md-3">
                        <div class="req_inner">
                            <div class="topbar">
                                <b>{{ req.book.subject.code }}{{ req.book.id }}</b>
                                {{ req.book.title }}
                                <div class="toggler"><i class="fa fa-arrow-right"></i></div>
                            </div>
                            <div class="body"> 
                                <div class="book">{{ req.book.title }}</div>
                                <div class="author"><span class="title">Author:&nbsp;</span>
                                    {{ req.book.author }}</div>
                                <div class="date"><span class="title">Date requested:&nbsp;</span>
                                    {{ req.request_date }}</div>
                                <div class="btn btn-warning">Cancel</div>                            
                            </div><br><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'library/dashboard.js' %}" type="text/javascript"></script>
{% endblock %}

library/templates/library/library.html
{% extends 'home/base.html' %}
{% block title %} Library {% endblock %}
{% block styles %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'library/library.css'%}">
{% endblock %}
{% block mininav %}
    {% include 'library/mininav.html' %}
{% endblock %}
{% block content %}
    <div class="container-fluid" id="position">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4" style="padding:10% 6% 0 6%">
                <form action="{% url 'library:search' %}" class="form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Look for books..." name="q">
                        <div class="input-group-btn">
                            <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-search"></i>Search</button>
                        </div>
                    </div>
                </form><br>
                <button class="btn btn-info tipsbutton" onclick="displaytips()">Tips</button>
                <div id="tips" class="row">
                    <ul>
                        <li>Enter only author's last name, not first name or initials.</li>
                        <li>Incomplete words like <b>Networ</b>king, <b>Forou</b>zan are okay.</li>
                        <li>Write <b>Fiction</b> to search for novels; <b>Mechanical</b> for Mechanical books, and so on. </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'library/library.js' %}" type="text/javascript"></script >
{% endblock %}

library/templates/library/mininav.html
<div class="container-fluid"style="margin-top:-30px">
    <div class="navbar-header" >
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#miniNavbar" style="float:left;background-color:transparent;margin-bottom:0px;margin-top:0px;margin-right:0px;padding-top:5px">
            <span class="glyphicon glyphicon-menu-hamburger"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="miniNavbar" style="padding-top:0px">
        <ul class="nav navbar-nav">
            {% if not 'library' in request.resolver_match.url_name %}
                <li><a  href="{% url 'library:library'%}">All Books</a></li>
            {% else %}
                <li class="active"><a  href="{% url 'library:library'%}">All Books</a></li>
            {% endif %}
            {% if not 'dashboard' in request.resolver_match.url_name %}
                <li><a  href="{% url 'library:user_dashboard'%}">Dashboard</a></li>
            {% else %}
                <li class="active"><a  href="{% url 'library:user_dashboard' %}">Dashboard</a></li>
            {% endif %}
            {% if request.user.is_superuser %}
                {% if not 'add' in request.resolver_match.url_name %}
                    <li><a href="{% url 'library:add'%}">Add a Book</a></li>
                {% else %}
                    <li class="active"><a href="{% url 'library:add'%}">Add a Book</a></li>
                {% endif %}
                {% comment %}
                    {% if not 'new' in request.resolver_match.url_name %}
                        <li><a href="{% url 'library:new'%}">Request Unregistered</a></li>
                    {% else %}
                        <li class="active"><a href="{% url 'library:new'%}">Request Unregistered</a></li>
                    {% endif %}
                {% endcomment %}
                {% if not 'admin_dash' in request.resolver_match.url_name %}
                    <li><a href="{% url 'library:admin_dash'%}">Admin Dashboard</a></li>
                {% else %}
                    <li class="active"><a href="{% url 'library:admin_dash'%}">Admin Dashboard</a></li>
                {% endif %}
            {% endif %}
        </ul>
        <div class="col-sm-3 col-md-3 col-xs-12" style="float:right">
            <form action="{% url 'library:search' %}" class="navbar-form" role="search">
                <div class="input-group">
                    {% if 'search' in request.resolver_match.url_name %}
                        <input type="text" id="query" class="form-control" placeholder="Search" name="q"  value="{{ query }}">
                    {% else %}
                        <input type="text" class="form-control" placeholder="Search" name="q">
                    {% endif %}
                    <div class="input-group-btn">
                        <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>